# Generated by Django 6.0 on 2025-12-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("end", "End To Do"),
                    ("not", "Not End To Do"),
                ],
                default="todo",
                max_length=10,
            ),
        ),
    ]
