# Generated by Django 6.0 on 2025-12-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
